kind: Deployment
apiVersion: apps/v1
metadata:
  name: expensetracker
spec:
  replicas: 1
  selector:
    matchLabels:
      name: expensetracker
  template:
    metadata:
      labels:
        name: expensetracker
    spec:
      containers:
        - name: expensetracker
          image: supermario128/expensetracker:latest
          ports:
            - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: expensetracker
spec:
  selector:
    name: expensetracker
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
