kind: Deployment
apiVersion: apps/v1
metadata:
  name: project
spec:
  replicas: 1
  selector:
    matchLabels:
      name: project
  template:
    metadata:
      labels:
        name: project
    spec:
      containers:
        - name: project
          image: supermario128/project:latest
          ports:
            - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: project
spec:
  selector:
    name: project
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
